stages:
  - test
variables:
      CYPRESS_CONFIG_FILE : "cypress.json"
      CYPRESS_PROJECT_PATH : "."
      CYPRESS_RECORD_KEY : ""
      CYPRESS_RECORDER : "spec"
      ADDITIONAL_OPTIONS : ""
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  #image: cypress/browsers:node12.14.1-chrome85-ff81
  image: node:16-buster
  stage: test
  script:
    - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests
    #- npx cypress run --browser firefox
    - >
        if [${CYPRESS_RECORD_KEY} != ""]; then
          export CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
          npx cypress run -P ${CYPRESS_PROJECT_PATH} -C ${CYPRESS_CONFIG_FILE} -r ${CYPRESS_RECORDER} ${ADDITIONAL_OPTIONS} --record
        else
          npx cypress run -P ${CYPRESS_PROJECT_PATH} -C ${CYPRESS_CONFIG_FILE} -r ${CYPRESS_RECORDER} ${ADDITIONAL_OPTIONS}
        fi
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
