name: Node.js CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/.npm
          # An explicit key for restoring and saving the cache
          key: ${{runner.os}}-build-${{env.cache-name}}-${{hashFiles('**/package-lock.json')}}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: | # Optional
            ${{runner.os}}-build-${{env.cache-name}}
            ${{runner.os}}-build-
            ${{runner.os}}-
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Archive Cypress outputs
        uses: actions/upload-artifact@v2
        with:
          # Artifact name. Optional, default is artifact
          name: cypress-outputs
          path: |
            cypress/videos/**/*.mp4
            cypress/screenshots/**/*.png
          if-no-files-found: error
          retention-days: 15
